<a href="https://colab.research.google.com/github/MaxenceAr/R-ponses_entrainement_code/blob/main/reponses_entrainement_base_code_java.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

In [ ]:
import numpy as np
vecteur=np.array([2,1,5])

In [ ]:
vecteur_trie = np.sort(vecteur)

In [ ]:
vecteur=np.array([2,1,5], dtype="int")

In [ ]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
x = np.arange(10)

In [ ]:
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x[0:10:2]

array([0, 2, 4, 6, 8])

In [ ]:
x[4:9]

array([4, 5, 6, 7, 8])

Observer ce qui suit

In [ ]:
x2 = np.array([[-1,1,-2],[-3,2,0]])
print(x2)

[[-1  1 -2]
 [-3  2  0]]


In [ ]:
print(x2<0)

[[ True False  True]
 [ True False False]]


In [ ]:
x = np.random.normal(size=10000)

# Conserver les valeurs dont la valeur absolue est supérieure à 1.96
valeurs_superieures = x[x > 1.96]

# Compter le nombre de valeurs supérieures à 1.96 en valeur absolue
nombre_valeurs_superieures = len(valeurs_superieures)

# Calculer la proportion dans l'ensemble initial
proportion_superieure = nombre_valeurs_superieures / len(x)

print(valeurs_superieures)
print(proportion_superieure)

[2.32010563 2.39170953 2.87423571 2.40663879 2.18980476 2.13402053
 2.51954735 2.15122617 2.22290683 2.38049275 3.1680327  2.22256287
 2.10508654 1.99281572 1.99387742 2.20710779 2.54751971 3.30442186
 2.59817329 2.3708682  2.00419694 2.09020668 2.01582733 1.97269099
 2.37649677 2.27537471 1.98334328 2.02616837 2.45092658 2.12542461
 2.11606466 1.99156677 2.88255975 2.19092701 2.0295003  2.17260639
 3.28750621 2.24439749 2.05613004 2.03309459 2.42756019 2.35238919
 1.99238702 3.24424481 2.11941323 2.89457901 2.79981946 2.26454572
 3.11513049 2.33559184 2.12551352 2.02645021 2.13804974 2.15357343
 2.05624285 2.52695103 2.58409554 2.07269049 2.62703549 1.99983278
 2.37804966 2.11494058 2.03899123 2.73386865 2.26449122 2.23964716
 2.02862998 2.4441567  2.39875831 1.99624453 2.21009912 2.20185221
 2.00453741 2.2035372  1.99328696 2.58622483 2.03894596 2.55614362
 2.98515343 2.31057263 2.08845023 2.20804315 2.02344646 2.66564759
 3.04566581 2.18240624 2.5517683  1.99504283 2.7552337  1.9684

# Panda**s**

In [ ]:
import pandas as pd
chemin_fichier = '/content/sample_data/GES par commune ADEME.csv'
GES_ADEME=pd.read_csv(chemin_fichier)
#Le data frame s'appelle maintenant GES_ADEME

In [ ]:
GES_ADEME.head(7)

INSEE commune                  Commune  Agriculture  Autres transports  \
0         01001  L'ABERGEMENT-CLEMENCIAT  3711.425991                NaN   
1         01002    L'ABERGEMENT-DE-VAREY   475.330205                NaN   
2         01004        AMBERIEU-EN-BUGEY   499.043526         212.577908   
3         01005      AMBERIEUX-EN-DOMBES  1859.160954                NaN   
4         01006                  AMBLEON   448.966808                NaN   
5         01007                 AMBRONAY  4390.996698         132.968268   
6         01008                 AMBUTRIX   489.648726          60.233517   

   Autres transports international  CO2 biomasse hors-total      Déchets  \
0                              NaN               432.751835   101.430476   
1                              NaN               140.741660   140.675439   
2                              NaN             10313.446515  5314.314445   
3                              NaN              1144.429311   216.217508   
4                              NaN                77.033834    48.401549   
5                              NaN              3067.245459  6144.186081   
6                              NaN               558.055709    98.388885   

      Energie  Industrie hors-énergie   Résidentiel       Routier  \
0    2.354558                6.911213    309.358195    793.156501   
1    2.354558                6.911213    104.866444    348.997893   
2  998.332482             2930.354461  16616.822534  15642.420313   
3   94.182310              276.448534    663.683146   1756.341319   
4         NaN                     NaN     43.714019    398.786800   
5  122.437003              359.383094   1898.638273  22481.123575   
6    2.354558                6.911213    495.393592   3616.168396   

      Tertiaire  
0    367.036172  
1    112.934207  
2  10732.376934  
3    782.404357  
4     51.681756  
5   2789.133106  
6    356.029873

In [ ]:
x = pd.DataFrame(
    {'prix': np.random.uniform(size = 5),
     'quantite': [i+1 for i in range(5)]
    },
    index = ['yaourt','pates','riz','tomates','gateaux']
)

In [ ]:
y = pd.DataFrame(
    {'prix': [np.nan, 0, 1, 2, 3],
     'quantite': [i+1 for i in range(5)]
    },
    index = ['tomates','yaourt','gateaux','pates','riz']
)
y



In [ ]:
print(x+y)

Il est possible de supprimer les valeurs manquantes grâce à dropna(). Cette méthode va supprimer toutes les lignes où il y a au moins une valeur manquante. Il est aussi possible de supprimer seulement les colonnes où il y a des valeurs manquantes dans un DataFrame avec dropna() avec le paramètre axis=1 (par défaut égal à 0).

In [ ]:
GES_ADEME.shape

In [ ]:
GES_ADEME['Commune'].nunique()
#GES_ADEME.nunique() pour toutes les colonnes en même temps.

In [ ]:
GES_ADEME.columns

In [ ]:
GES_ADEME.describe()

In [ ]:
GES_ADEME.isna().sum()

In [ ]:
print(GES_ADEME['Commune'])

In [ ]:
print(GES_ADEME.iloc[1, :])

In [ ]:
GES_ADEME['x'] = np.log(df['Agriculture'])

In [ ]:
GES_ADEME[GES_ADEME['Agriculture']>2000]

df[['Autres transports','Energie']]

table1.merge(table2, left_on = 'id', right_on = 'x')


In [ ]:
GES_ADEME = GES_ADEME.sort_values("Résidentiel", ascending = False)

In [ ]:
GES_ADEME[GES_ADEME['Commune'].apply(lambda s: len(s)>40)]

En Python, le mot-clé lambda est utilisé pour déclarer une fonction anonyme, raison pour laquelle ces fonctions sont appelées « fonctions lambda«.

Syntaxe :lambda arguments: expression

De façon générale les fonctions anonymes sont utilisées lorsqu’il n’est pas nécessaire de nommer une fonction. En effet, il y a aucun intérêt de nommer une fonction qu’on utilisera qu’une fois 🤔. Mieux, on peut dire que l’utilisation de fonctions lambda est une question de style. Leur utilisation n’est jamais la seule façon de résoudre un problème ; chaque fonction anonyme pourrait plutôt être définie comme une fonction classique (régulière).

# Graphes

In [ ]:
GES_ADEME_without_balance.hist(figsize=(20,15))
plt.show()

# ML